apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: digilians
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sondosomarr/digilians-backend
        env:
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "admin1234"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "learning_platform"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: digilians
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
